{
  "comments": [
    {
      "key": {
        "uuid": "b6dbf812_50333c96",
        "filename": "init/builtins.cpp",
        "patchSetId": 7
      },
      "lineNbr": 1210,
      "author": {
        "id": 1132673
      },
      "writtenOn": "2019-12-19T15:14:21Z",
      "side": 1,
      "message": "nit: just \u0027ret\u0027 or \u0027success\u0027?",
      "range": {
        "startLine": 1210,
        "startChar": 13,
        "endLine": 1210,
        "endChar": 34
      },
      "revId": "7662ce0f62d33017088b931936a5dd4a86a83a50",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "800587f8_298a70e6",
        "filename": "init/mount_namespace.cpp",
        "patchSetId": 7
      },
      "lineNbr": 241,
      "author": {
        "id": 1132673
      },
      "writtenOn": "2019-12-19T15:14:21Z",
      "side": 1,
      "message": "\"LOG\" as errno is already included in the error.",
      "range": {
        "startLine": 241,
        "startChar": 12,
        "endLine": 241,
        "endChar": 16
      },
      "revId": "7662ce0f62d33017088b931936a5dd4a86a83a50",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    }
  ]
}