{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "d6ef126d_7aef9971",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1724998
      },
      "writtenOn": "2021-01-21T06:30:29Z",
      "side": 1,
      "message": "I couldn\u0027t reproduce the kernel crash. I am investigating that separately; but this should address the daemon crash.",
      "revId": "ae0783f4c7a9263450c2bc92b69583220f479753",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}