{
  "comments": [
    {
      "key": {
        "uuid": "8c3d82b2_ed07349a",
        "filename": "init/init.cpp",
        "patchSetId": 1
      },
      "lineNbr": 826,
      "author": {
        "id": 1064128
      },
      "writtenOn": "2017-02-24T19:32:09Z",
      "side": 1,
      "message": "PLOG?  Is there a relevant errno for this log?",
      "range": {
        "startLine": 826,
        "startChar": 8,
        "endLine": 826,
        "endChar": 12
      },
      "revId": "b1fbfcc73f8d2049271bf2aa663371454d834b07",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9a53196a_cc1ba4ba",
        "filename": "init/init.cpp",
        "patchSetId": 1
      },
      "lineNbr": 828,
      "author": {
        "id": 1064128
      },
      "writtenOn": "2017-02-24T19:32:09Z",
      "side": 1,
      "message": "It\u0027s possible we may have called device_init() despite failing and need device_close() here, right?",
      "revId": "b1fbfcc73f8d2049271bf2aa663371454d834b07",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    }
  ]
}