{
  "comments": [
    {
      "key": {
        "uuid": "cd26414f_79483f77",
        "filename": "fs_mgr/fs_mgr.c",
        "patchSetId": 2
      },
      "lineNbr": 565,
      "author": {
        "id": 1003966
      },
      "writtenOn": "2014-01-14T18:56:29Z",
      "side": 1,
      "message": "if partition_wiped() executes, it has the potential to modify errno, making the strerror(errno) on line 579 print a misleading value.\n\nCan you save errno before this block to avoid the problem?",
      "revId": "bd9b235987083c158532dca009cab092816b67e0",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "ad810d4e_db261f4d",
        "filename": "fs_mgr/fs_mgr.c",
        "patchSetId": 2
      },
      "lineNbr": 565,
      "author": {
        "id": 1013433
      },
      "writtenOn": "2014-01-14T19:22:26Z",
      "side": 1,
      "message": "Looking back at my logs the code never went this route, I went the second branch below. __mount() is safe from my observation. I think the proper fix is to move this up to under the mount.. not on this branch.",
      "parentUuid": "cd26414f_79483f77",
      "revId": "bd9b235987083c158532dca009cab092816b67e0",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    }
  ]
}