{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "eb685187_52a4aaca",
        "filename": "/COMMIT_MSG",
        "patchSetId": 4
      },
      "lineNbr": 7,
      "author": {
        "id": 1724998
      },
      "writtenOn": "2023-12-06T05:30:27Z",
      "side": 1,
      "message": "How was this bug observed ? Any test failures or during local ota tests ?",
      "revId": "d45c50911f989caacc6c46f79ee2e4fd66615c65",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "6b9646e8_b4761103",
        "filename": "/COMMIT_MSG",
        "patchSetId": 4
      },
      "lineNbr": 7,
      "author": {
        "id": 1710792
      },
      "writtenOn": "2023-12-06T05:34:40Z",
      "side": 1,
      "message": "We currently don\u0027t have any automated OTA tests for COW v3, so this is discovered in local testing. The added test case can easily reproduce the failure(revert my changes in writer_v3.cpp, keep the test_v3.cpp testcase, then `atest cow_api_test` .",
      "parentUuid": "eb685187_52a4aaca",
      "revId": "d45c50911f989caacc6c46f79ee2e4fd66615c65",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}