{
  "comments": [
    {
      "key": {
        "uuid": "d9065c9a_62bafddc",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 9,
      "author": {
        "id": 1003224
      },
      "writtenOn": "2017-04-20T00:03:02Z",
      "side": 1,
      "message": "that doesn\u0027t seem right, since the call is just a couple of lines above. seems like libprocessgroup isn\u0027t always setting errno? but it looks like libprocessgroup will already have logged in every case that would set errno?\n\nso i think this patch is fine but the rationale in the checkin comment is wrong? :-)",
      "revId": "d8f11d33115432dba61565134a9bf8a748193194",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    }
  ]
}